import { resolve } from 'node:path';

import { defineConfig } from 'vitest/config';

export default defineConfig({
  resolve: {
    alias: {
      '@': resolve('src'),
      '@shared': resolve('shared'),
    },
  },
  test: {
    environment: 'node',
    include: [
      'scripts/**/*.test.ts',
      'shared/**/*.test.ts',
      'electron/**/*.test.ts',
      'scripts/**/*.test.ts',
      'src/lib/**/*.test.ts',
      'src/hooks/**/*.test.ts',
      'src/layout/**/*.test.tsx',
      'src/cache/**/*.test.ts',
      'src/features/agent/ui-diff-view/**/*.test.ts',
      'src/features/agent/ui-markdown-content/**/*.test.ts',
      'src/features/agent/ui-message-stream/**/*.test.ts',
      'src/features/agent/ui-message-input/**/*.test.tsx',
      'src/features/agent/ui-permission-bar/**/*.test.tsx',
      'src/features/agent/ui-question-options/**/*.test.ts',
      'src/features/agent/ui-question-options/**/*.test.tsx',
      'src/features/agent/ui-add-permission-modal/**/*.test.tsx',
      'src/features/agent/task-message-manager/**/*.test.tsx',
      'src/features/agent/ui-worktree-actions/**/*.test.ts',
      'src/features/agent/utils-backend-model-selection/**/*.test.ts',
      'src/features/changelog/**/*.test.tsx',
      'src/features/common/ui-azure-html-content/**/*.test.tsx',
      'src/features/common/ui-inline-comments/**/*.test.ts',
      'src/features/common/ui-file-diff/**/*.test.ts',
      'src/features/common/ui-file-diff/**/*.test.tsx',
      'src/features/common/ui-spreadsheet-viewer/**/*.test.ts',
      'src/features/common/ui-prompt-textarea/**/*.test.ts',
      'src/features/common/ui-mermaid-diagram/**/*.test.tsx',
      'src/features/common/ui-ai-skill-slot/**/*.test.tsx',
      'src/features/common/ui-external-directories/**/*.test.tsx',
      'src/features/work-item/**/*.test.ts',
      'src/features/work-item/**/*.test.tsx',
      'src/features/project/ui-project-settings/**/*.test.ts',
      'src/features/project/ui-run-commands-config/**/*.test.ts',
      'src/features/project/ui-run-commands-config/**/*.test.tsx',
      'src/features/project/ui-work-item-title-parser-settings/**/*.test.ts',
      'src/features/settings/**/*.test.tsx',
      'src/features/common/ui-video-gif-converter/**/*.test.ts',
      'src/features/mobile-preview/**/*.test.ts',
      'src/features/mobile-preview/**/*.test.tsx',
      'src/features/new-task/ui-prompt-composer/**/*.test.ts',
      'src/common/ui/handlebars-editor/**/*.test.ts',
      'src/features/work-activity/**/*.test.ts',
      'src/features/work-activity/**/*.test.tsx',
      'src/features/run-commands/**/*.test.ts',
      'src/features/run-commands/**/*.test.tsx',
      'src/features/pull-request/**/*.test.ts',
      'src/features/pull-request/**/*.test.tsx',
      'src/features/task/**/*.test.ts',
      'src/features/task/**/*.test.tsx',
      'src/features/calendar/**/*.test.ts',
      'src/features/calendar/**/*.test.tsx',
      'src/features/feed/**/*.test.tsx',
      'src/features/work-item/ui-azure-board-overlay/**/*.test.tsx',
      'src/features/work-item/ui-work-item-board/**/*.test.ts',
      'src/features/work-item/ui-parsed-work-item-title/**/*.test.tsx',
      'src/stores/**/*.test.ts',
    ],
    setupFiles: ['./vitest.setup.ts'],
  },
});
