import { describe, expect, it } from 'vitest';

import { isLikelyFileMutatingCommand } from './utils-shell-edit-detection';

describe('isLikelyFileMutatingCommand', () => {
  it.each([
    "sed -i '' 's/a/b/' src/index.ts",
    'sed -i.bak s/a/b/ file.ts',
    'perl -pi -e "s/a/b/" file.ts',
    'python3 fix.py',
    'node scripts/codemod.js',
    'echo hi > out.txt',
    'cat file >> other',
    'grep foo bar | tee out.txt',
    'git apply patch.diff',
    'git checkout -- src/',
    'git stash',
    'mv a b',
    'rm -rf dist',
    'cp -r a b',
    'mkdir -p src/new',
    'touch file.ts',
    "cat <<'EOF' > file.ts\nhello\nEOF",
    'pnpm exec prettier --write .',
    'sudo rm -rf /tmp/x',
    'FOO=1 python3 script.py',
    'ls && sed -i s/a/b/ f.ts',
    'bash -c "sed -i s/a/b/ f.ts"',
    'sh -c \'rm -rf dist\'',
    'find . -name "*.snap" -delete',
    'find . -name "*.ts" -exec sed -i s/a/b/ {} +',
    'ls | xargs sed -i s/a/b/',
    'timeout 30 python3 codemod.py',
    'chmod +x scripts/run.sh',
    'curl -o vendor.js https://example.com/a.js',
    'prettier --write src',
    'echo "$(sed -i s/a/b/ f.ts)"',
    'cd src && sed -i s/a/b/ f.ts',
    'git -C /repo checkout .',
    'git -c core.pager=cat reset --hard',
    'git clean -fd',
    'npm run build',
    './scripts/fix.sh',
    'bash scripts/codemod.sh',
    'make build',
    'tar -xzf archive.tgz',
  ])('detects %j as mutating', (command) => {
    expect(isLikelyFileMutatingCommand(command)).toBe(true);
  });

  it.each([
    '',
    '   ',
    'ls -la',
    "sed -n '1,60p' src/index.ts",
    'grep -n "subCommands" src/index.ts | head',
    'git status',
    'git diff --stat',
    'git log -5',
    'cat package.json',
    'pnpm',
    'echo "sed -i s/a/b/"',
    "grep -n '>' file.ts",
    'find . -name "*.tmp"',
    'python3',
    'node -v',
    'python3 --version',
    'git stash list',
    'git clean -n',
    'find . -name "*.tmp" -type f',
    'curl -s https://example.com',
    'bash -c "ls -la"',
    'timeout 30 pnpm --version',
    'git clean -n -d',
    'git stash show -p',
    'git -C /repo status',
    'git checkout --help',
  ])('treats %j as read-only', (command) => {
    expect(isLikelyFileMutatingCommand(command)).toBe(false);
  });
});
